import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getSessionUser } from '@/app/lib/auth'; // Pastikan path ini benar
import Navbar from '@/app/component/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyCourse Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // 1. Ambil raw data dari server
  const rawUser = await getSessionUser();

  // 2. SANITASI DATA (PENTING!)
  // Kita buat object baru yang DIJAMIN aman untuk Client Component.
  // Jika rawUser ada, kita ambil field penting saja. Jika null, biarkan null.
  const safeUser = rawUser ? {
    id: rawUser.id,
    name: rawUser.name,
    email: rawUser.email,
    image: rawUser.image,
    role: rawUser.role,
    // Jangan sertakan createdAt / updatedAt kecuali di-convert ke string:
    // createdAt: rawUser.createdAt?.toString() 
  } : null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 3. Kirim 'safeUser' yang sudah bersih */}
        <Navbar user={safeUser} /> 
        {children}
      </body>
    </html>
  );
}